import { useEffect, useState } from 'react';
import { Package, Store, WalletCards } from 'lucide-react';
import { getCompanyDealers, getCompanyProducts, getCompanyProfile, type CompanyProfileApi } from '../../services/company.service';

export function CompanyDashboard() {
  const [stats, setStats] = useState({ products: 0, dealers: 0, activeDealers: 0 });
  const [profile, setProfile] = useState<CompanyProfileApi | null>(null);
  useEffect(() => { Promise.all([getCompanyProducts(), getCompanyDealers(), getCompanyProfile()]).then(([products, dealers, company]) => { setStats({ products: products.length, dealers: dealers.length, activeDealers: dealers.filter((dealer) => dealer.companyDealerStatus === 'ACTIVE').length }); setProfile(company); }); }, []);
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-primary">Company overview</p><h1 className="mt-1 font-display text-3xl font-extrabold">{profile?.companyName || 'Company'} Dashboard</h1><p className="mt-2 text-sm text-muted-foreground">A central workspace for your products and dealer network.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Package} label="Company products" value={stats.products} /><Metric icon={Store} label="Assigned dealers" value={stats.dealers} /><Metric icon={Store} label="Active dealers" value={stats.activeDealers} /><Metric icon={WalletCards} label="Subscription" value={profile?.subscription?.isActive ? 'Active' : 'Trial / Pending'} /></section><section className="rounded-2xl border border-border bg-card p-6 shadow-soft"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Ownership model</p><h2 className="mt-2 font-display text-xl font-bold">One company catalogue</h2><p className="mt-2 text-sm text-muted-foreground">Products created by your company, assigned dealers, or admins under this company appear together in My Products.</p></section></div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Package; label: string; value: string | number }) { return <div className="rounded-2xl border border-border bg-card p-5 shadow-soft"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 font-display text-2xl font-extrabold">{value}</p></div>; }
